name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build-amd64:
    name: Build and run tests on Linux amd64
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: read
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: make
      run: make -j2
    - name: running testsuite
      run: make test -j2
    - name: make dist
      run: make dist
    - name: Archive ATR
      uses: actions/upload-artifact@v4
      with:
       name: fastbasic.atr
       path: build/fastbasic.atr
    - name: Archive ZIP Linux amd64
      uses: actions/upload-artifact@v4
      with:
       name: fastbasic-linux-amd64.zip
       path: build/fastbasic.zip

  build-macos-M1:
    name: Build and run tests on MacOS M1 (ARM64)
    runs-on: macos-14
    permissions:
      contents: read
      pull-requests: read
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: make
      run: |
        gcc -v
        make -j2
    - name: running testsuite
      run: make test -j2
    - name: make dist
      run: make dist
    - name: Archive ZIP MacOS ARM
      uses: actions/upload-artifact@v4
      with:
       name: fastbasic-macos-arm64.zip
       path: build/fastbasic.zip

  build-windows:
    name: Build and run tests on Windows
    runs-on: windows-2022
    permissions:
      contents: read
      pull-requests: read
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Setup 32-bit compiler
      run: |
        echo "C:\msys64\mingw32\bin" >> $GITHUB_PATH
        echo "C:\msys64\usr\bin" >> $GITHUB_PATH
        echo "CC=i686-w64-mingw32-gcc" >> "$GITHUB_ENV"
      shell: bash
    - name: Install packages
      run: |
        export
        pacman -Sy --noconfirm --noprogressbar --needed zip mingw-w64-i686-gcc mingw-w64-x86_64-gcc
      shell: bash
    - name: make
      run: |
        i686-w64-mingw32-gcc -v
        make OPTFLAGS="-O2 -static" -j2
      shell: bash
    - name: running testsuite
      run: make test -j2
    - name: make dist
      run: make dist
      shell: bash
    - name: Archive ZIP Windows 32-bit
      uses: actions/upload-artifact@v4
      with:
       name: fastbasic-windows-32bit.zip
       path: build/fastbasic.zip
    - name: make distclean
      run: make distclean
      shell: bash
    - name: Setup 64-bit compiler
      run: |
        echo "CC=x86_64-w64-mingw32-gcc" >> "$GITHUB_ENV"
        echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
      shell: bash
    - name: make
      run: |
        x86_64-w64-mingw32-gcc -v
        make OPTFLAGS="-O2 -static" -j2
      shell: bash
    - name: running testsuite
      run: make test -j2
      shell: bash
    - name: make dist
      run: make dist
      shell: bash
    - name: Archive ZIP Windows 64-bit
      uses: actions/upload-artifact@v4
      with:
       name: fastbasic-windows-64bit.zip
       path: build/fastbasic.zip

